services:

  postgres:
    image: postgres:16-alpine
    # image: 'pgvector/pgvector:0.8.0-pg17'
    container_name: midona-postgres
    environment:
      POSTGRES_USER: midona
      POSTGRES_PASSWORD: midona
      POSTGRES_DB: midona
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'midona', '-U', 'midona']
      retries: 3
      timeout: 5s

  redis:
    image: redis:7-alpine
    container_name: midona-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  redis-data:
